"""Engine modules shared by architecture proposal and execution."""

from occam.engine.architect import (
    ARCHITECT_MODEL_KEY,
    DOMAIN_RULE_HEADING,
    Architect,
    ArchitectContext,
    ArchitectError,
    propose_architecture,
)
from occam.engine.baseline import BASELINE_MODEL, BaselineResult, run_baseline
from occam.engine.compare import compare_runs, format_compare
from occam.engine.diagnose import (
    DIAGNOSE_MODEL_KEY,
    DiagnosisPayload,
    DiagnosisResult,
    LessonProposal,
    LessonWriter,
    diagnose,
    lesson_passes_leak_guard,
)
from occam.engine.executor import (
    ArchitectureError,
    CycleError,
    Executor,
    ExecutorError,
    ToolBinding,
    descendants,
    normalize_registry,
    resolve_grader,
    sentinel_for,
    topological_levels,
    validate_architecture,
    wilson_ci,
)
from occam.engine.loop import RunConfig, RunEngine, RunOutcome, run, run_task
from occam.engine.mutate import (
    PRUNABLE_VERDICTS,
    Mutation,
    MutationApplication,
    MutationError,
    MutationType,
    apply_architecture_mutation,
    apply_mutation,
    mutate,
    revert_mutation,
)
from occam.engine.pass3 import Pass3Result, run_pass3

__all__ = [
    "ARCHITECT_MODEL_KEY",
    "ArchitectureError",
    "Architect",
    "ArchitectContext",
    "ArchitectError",
    "CycleError",
    "DOMAIN_RULE_HEADING",
    "Executor",
    "ExecutorError",
    "ToolBinding",
    "Mutation",
    "MutationApplication",
    "MutationError",
    "MutationType",
    "PRUNABLE_VERDICTS",
    "apply_architecture_mutation",
    "apply_mutation",
    "descendants",
    "mutate",
    "propose_architecture",
    "revert_mutation",
    "normalize_registry",
    "resolve_grader",
    "sentinel_for",
    "topological_levels",
    "validate_architecture",
    "wilson_ci",
    "BASELINE_MODEL",
    "BaselineResult",
    "run_baseline",
    "compare_runs",
    "format_compare",
    "DIAGNOSE_MODEL_KEY",
    "DiagnosisPayload",
    "DiagnosisResult",
    "LessonProposal",
    "LessonWriter",
    "diagnose",
    "lesson_passes_leak_guard",
    "RunConfig",
    "RunEngine",
    "RunOutcome",
    "run",
    "run_task",
    "Pass3Result",
    "run_pass3",
]
